project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

  resources:
    - "files/**"

    # Things that need to be at the site root
    - ".htaccess"
    - "LiveSearchSiteAuth.xml"
    # - "keybase.txt"
    - "y_key_31e0c4105fc75710.html"
    - "pgp_ath.asc.txt"

execute:
  freeze: auto

# bibliography: files/bib/references.bib
# csl: files/bib/chicago-author-date.csl

# Metadata stuff
# pagetitle: "{{< meta title >}} | {{< meta website.title >}}"
# description-meta: "{{< meta description >}}"
# author-meta: "Guorui Zhong"

website:
  title: "Guorui Zhong"
  description: "Guorui Zhong"
  favicon: "/files/profiles/z_512x512.png"
  site-url: "https://guoruizhong.github.io/"
  repo-url: "https://github.com/guoruizhong/guoruizhong.github.io"

  # google-analytics: "UA-527449-5"

  # twitter-card: 
  #   image: "/files/profiles/twitter-card-large.png"
  #   card-style: summary_large_image
  #   creator: "@andrewheiss"
  #   site: "@andrewheiss"

  # open-graph: 
  #   image: "/files/profiles/twitter-card-large.png"
  #   locale: en_US
  
  navbar:
    pinned: true

    right:
      - icon: activity
        aria-label: activity
        # text: "Learning"
        href: "now/index.qmd"
      # - text: "Uses"
      #   file: uses/index.qmd
      # - text: "About"
      #   href: "index.qmd"
      # - text: "CV"
      #   href: "cv/index.qmd"
      # - text: "Posts"
      #   file: "blog/index.qmd"
        # file: "blog/index.qmd"
      # - text: "Research"
      #   file: research/index.qmd
      # - text: "Teaching"
      #   href: "teaching/index.qmd"
      # - text: "Talks"
      #   href: "talks/index.qmd"
    
    # right:
      # - icon: rss
      #   aria-label: rss
      #   href: atom.xml
      - icon: envelope
        aria-label: email
        href: "mailto:zhonggr@bii.a-star.edu.sg"
      # - icon: twitter
      #   aria-label: twitter
      #   href: https://twitter.com/andrewheiss
      #   # rel: me
      # - icon: mastodon
      #   aria-label: mastodon
      #   href: https://fediscience.org/users/andrew/
      #   # rel: me
        # rel: me
      # - icon: youtube
      #   aria-label: youtube
      #   href: https://www.youtube.com/andrewheiss
      #   # rel: me
      # - icon: postage-heart-fill
      #   aria-label: family
      #   href: https://www.heissatopia.com/
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/guorui-zhong-754761185/
      - icon: github
        aria-label: github
        href: https://github.com/guoruizhong

  
  page-footer:
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2021-2023 Guorui Zhong ~ Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>

format:
  html:
    theme:
      - html/me.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    # highlight-style: github-dark
    highlight-style: dracula
    # highlight-style: monokai
