---
title: Wiki
date: 2023-04-09
title-block-banner: "#212529"
published-title: Last updated
toc: true
toc-location: left
toc-title: "Contents"
---

These are the collections of things that I beleived useful in my daily researh work.
  
## To be a biologist

- [Bioturing](https://blog.bioturing.com/)
- [iBiology - Bringing the world's best biology to you, for free!](https://www.ibiology.org/)
- [Sequence Variant Nomenclature](http://varnomen.hgvs.org/)
- [Encyclopedia Britannica](https://www.britannica.com/)
- [Labpedia.net](https://labpedia.net/)
- [The bumbling chemist](https://thebumblingbiochemist.com/)
- [ToxTutor](https://www.toxmsdt.com/0-toxtutor-home.html)

## Researh Labs

- <https://www.jax.org> - Leading the research for tomorrow's cures
- <https://www.snijderlab.org/> - Use systems biology to discover things about cells.
- <https://zlab.bio/> - Zhang Feng Biological Discovery & Engineering
- <https://www.ciccialab.com/> - Genome Integrity and Genome Editing
- <https://sizunjianglab.com> - Investigate host-disease interaction
- <http://rafalab.dfci.harvard.edu/> - Development of statistical tools
- <https://hostmicrobe.org/> - Study the biological basis of diseases caused by microbes
- <https://cheesemanlab.wi.mit.edu/> - World of cell division
- <https://blainey.mit.edu/> - Pooled optical genetic screening in human cells
- <https://marsonlab.org/> - Decoding and rewriting human immune cells with CRISPR
- <https://liulab-dfci.github.io/> - Computational methods for the design (SSC), analysis (MAGeCK), hit prioritization (NEST), and visualization (VISPR) of genome-wide CRISPR screens


## Research Proposal

- [NMRC | Open Fund - Young Individual Research Grant](https://www.nmrc.gov.sg/grants/competitive-research-grants/of-yirg)
- [Funding Opportunities - Abramson Cancer Center | Penn Medicine](https://www.pennmedicine.org/cancer/cancer-research/for-researchers/investigators-only/funding-opportunities)
- [Write Your Research Plan](https://www.niaid.nih.gov/grants-contracts/write-research-plan)

## Paper writting

- [The underappreciated art of creating publication-quality figures](https://www.embopress.org/doi/abs/10.15252/embr.202255114)


## Useful Tools

- [DIY.transcriptomics](https://diytranscriptomics.com/lab/)
- [ProteinPaint](https://proteinpaint.stjude.org/)
- [Hiplot](https://hiplot.cn/)
- [Free Icons and Stickers](https://www.flaticon.com/)
- [Bootstrap Icons](https://icons.getbootstrap.com/)
- [Blood PBMCs](https://www.miltenyibiotec.com/US-en/resources/macs-handbook/human-cells-and-organs/human-cell-sources/blood-human.html)
- [distill](https://distill.pub/)

## Learning R

- [An Introduction to Statistical Learning](https://www.statlearning.com/)
- [R for Data Science (2e)](https://r4ds.hadley.nz/)
- [R Graphics Cookbook, 2nd edition](https://r-graphics.org/)
- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/)
- [The Epidemiologist R Handbook](https://epirhandbook.com/en/index.html)
- [Modern Statistics for Modern Biology](https://web.stanford.edu/class/bios221/book/)
- [Data Analysis and Prediction Algorithms with R](http://rafalab.dfci.harvard.edu/dsbook/)
- [Bioinformatics Training & Education Program](https://bioinformatics.ccr.cancer.gov/btep/)
- [Saving R Graphics across OSs](https://www.jumpingrivers.com/blog/r-graphics-cairo-png-pdf-saving/) 
- [Tutorial on Advanced Stats and Machine Learning with R](http://r-statistics.co/)
- [Publication ready plots using ggpubr](https://jeweljohnsonj.github.io/jeweljohnson.github.io/project7.html)
- [datanovia](https://www.datanovia.com/en/)
- [Data Analysis in Genome Biology](https://girke.bioinformatics.ucr.edu/GEN242/)
- [Data Viz with Python and R](https://datavizpyr.com/category/r/)

## Bioinformatics Training

- [National Cancer Institute: Bioinformatics Training & Education Program](https://bioinformatics.ccr.cancer.gov/btep/)
- [High dimensional statistics with R Introduction to high-dimensional data](https://carpentries-incubator.github.io/high-dimensional-stats-r/aio/index.html)
- [Bioinformatics Training at the Harvard Chan Bioinformatics Core](https://hbctraining.github.io/main/)

## Nice Blogs

- <https://www.andrewheiss.com/blog/>
- <https://www.andreashandel.com/>
- <https://renkun.me/>
- <https://morphoscape.wordpress.com/category/tech/>
- <https://albert-rapp.de/>
- <https://jokergoo.github.io/>

## CRISPR

- [Guide Design Resources](https://zlab.bio/guide-design-resources)
- [New CRISPR Method Allows Scientists to Understand Impact of Subtle Mutations](https://www.cuimc.columbia.edu/news/new-crispr-method-allows-scientists-understand-impact-subtle-mutations)
- [CRISPR Transfection Protocols Guide: How To Select The Best Method](https://www.synthego.com/guide/how-to-use-crispr/transfection-protocols)
- [How To Use CRISPR: Your Guide to Successful Genome Engineering](https://www.synthego.com/guide/how-to-use-crispr)
- [The Ultimate Guide To CRISPR: Mechanism, Applications, Methods & More](https://www.synthego.com/learn/crispr)
- [Irregular Protein Expression After CRISPR Edits: Troubleshooting Tips](https://www.synthego.com/blog/crispr-irregular-protein-expression)
- [CRISPR Editing in Primary Cells](https://www.synthego.com/crispr-primary-cells)
- [CrispR screen analysis using R and Bioconductor](https://rockefelleruniversity.github.io/RU_CrisprScreen/presentations/singlepage/crisprscreen.html#Crispr_Screenining_analysis_in_R)

## Books

- [R for Data science](https://r4ds.hadley.nz/)
- [R Graphics Cookbook, 2nd edition](https://r-graphics.org/)
- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/)
- [Modern Statistics for Modern Biology](https://web.stanford.edu/class/bios221/book/)
- [An Introduction to Statistical Learning](https://www.statlearning.com/)
- [Functional Programming](https://dcl-prog.stanford.edu/)
- [The Epidemiologist R Handbook](https://epirhandbook.com/en/index.html)
- [Data Analysis and Prediction Algorithms with R](http://rafalab.dfci.harvard.edu/dsbook/)
- [Data Analysis in Genome Biology](https://girke.bioinformatics.ucr.edu/GEN242/)
- [PH525x series - Biomedical Data Science](http://genomicsclass.github.io/book/)