---
title: What I use in my research workflow
date: 2022-12-26
# description-meta: Andrew Heiss is working on a bunch of exciting and groundbreaking projects
title-block-banner: "#212529"
published-title: Last updated
toc: true
toc-location: left
toc-title: "Contents"
---


I do both wet-lab and dry-lab for my research and work. So my setup should support the following well:
  
## Writing

- [Microsoft 365](https://www.office.com/) - Prepare presentations using Powerpoint; Write paper, report, grant writing using Word as required.
- [LibreOffice](https://www.libreoffice.org/) - Draw schematics for specific workflow in research.
- [Eudic](https://www.eudic.net/v4/en/app/eudic) - For lookup and translation.
- [Snipaste](https://www.snipaste.com/) - For screenshot. 
- [Typora](https://typora.io/) - For writting notebooks using Markdown.
- [Zotero](https://www.zotero.org/) - For research and reference management, and  [jianguoyun](https://www.jianguoyun.com/) to sync the attachment files.  
- [Notion](https://www.notion.so) - Save some web bookmark and notebook
- [Inkscape](https://inkscape.org/) - Edit figures for publication
- [Fiji/ImageJ](https://imagej.net/software/fiji/) and [GIMP](https://www.gimp.org/) - Edit images for publication
- [cellXpress](https://cellxpress.org/) - Cellular and tissue image process

## Development

- [R](https://www.r-project.org/) - For most of my statistical computing and visualization. 
- [Python](https://www.python.org/) - Learning machnine learning to use python as a beginner.
- [Visual Studio Code](https://code.visualstudio.com/) - R coding environment   
- [GitHub](https://github.com/guoruizhong) - For website deploy. I start to write notebooks and deploy it to Github.
- [macFUSE](https://osxfuse.github.io/) - To mount remote files from Remote server via SSHFS
- [Quarto](https://quarto.org/) - Write notebook and make website
